# Generated by Django 5.1.7 on 2025-05-05 13:50
from django.db import migrations

def insert_default_forms(apps, schema_editor):
    Form = apps.get_model('Produit', 'Form')
    default_forms = [
        'Comprimé',
        'Gélule',
        'Sirop',
        'Pommade',
        'Injection',
        'Suppositoire',
        'Comprimé effervescent',
        'Solution buvable',
        'Crème',
        'Spray nasal'
    ]
    for form in default_forms:
        Form.objects.get_or_create(name=form)

class Migration(migrations.Migration):

    dependencies = [
        ('Produit', '0001_initial'),  # Remplace XXXX par la dernière migration précédente
    ]

    operations = [
        migrations.RunPython(insert_default_forms),
    ]
