# Generated by Django 5.1.7 on 2025-06-14 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Produit', '0001_initial'),
        ('pharmacien', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacien.pharmacy'),
        ),
        migrations.AddField(
            model_name='productavailability',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Produit.form'),
        ),
        migrations.AddField(
            model_name='productavailability',
            name='pharmacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacien.pharmacy'),
        ),
        migrations.AddField(
            model_name='productavailability',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='Produit.product'),
        ),
    ]
