# Generated by Django 5.1.3 on 2025-04-12 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='forms',
        ),
        migrations.AlterField(
            model_name='productavailability',
            name='dosage',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='productavailability',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='Produit.product'),
        ),
    ]
