# Generated by Django 5.1.7 on 2025-06-15 20:47

from django.db import migrations
from django.db import migrations

def add_default_forms(apps, schema_editor):
    Form = apps.get_model('produits', 'Form')  # Remplace 'produits' par le nom de ton app
    default_forms = [
        "Comprimé",
        "Gélule",
        "Sirop",
        "Pommade",
        "Injection",
        "Suppositoire",
        "Crème",
        "Solution buvable",
        "Spray",
        "Patch",
    ]

    for form_name in default_forms:
        Form.objects.get_or_create(name=form_name)

class Migration(migrations.Migration):

    dependencies = [
        ('Produit', '0002_initial'),
    ]

    operations = [
    ]