# Generated by Django 5.1.3 on 2025-05-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produit', '0002_auto_20250505_1626'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='form',
            options={'verbose_name': 'Forme pharmaceutique', 'verbose_name_plural': 'Formes pharmaceutiques'},
        ),
        migrations.AlterField(
            model_name='form',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
