# Generated by Django 5.1.7 on 2025-05-19 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produit', '0004_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='expires_at',
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(),
        ),
    ]
