# Generated by Django 5.1.7 on 2025-06-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produit', '0004_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='est_expire',
            field=models.BooleanField(default=False),
        ),
    ]
