# Generated by Django 5.2.3 on 2025-07-05 02:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produit', '0005_product_est_expire'),
    ]

    operations = [
        migrations.AddField(
            model_name='productavailability',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
