# Generated by Django 5.1.7 on 2025-05-20 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produit', '0005_remove_notification_expires_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
