# Generated by Django 5.1.7 on 2025-05-20 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produit', '0006_delete_notification'),
        ('pharmacien', '0002_message_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pharmacien.pharmacy'),
            preserve_default=False,
        ),
    ]
