# Generated by Django 5.1.7 on 2025-05-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produit', '0007_product_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchhistory',
            name='session_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
