# Generated by Django 5.1.7 on 2025-06-13 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produit', '0008_alter_searchhistory_session_id'),
        ('pharmacien', '0006_delete_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productavailability',
            name='pharmacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacien.pharmacy'),
        ),
    ]
