# Generated by Django 5.1.7 on 2025-06-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expediteur_nom', models.CharField(help_text="Nom de l'expéditeur (utilisateur non authentifié ou nom fourni)", max_length=255)),
                ('expediteur_email', models.EmailField(help_text="Email de l'expéditeur", max_length=254)),
                ('sujet', models.CharField(max_length=255)),
                ('corps', models.TextField()),
                ('date_envoye', models.DateTimeField(auto_now_add=True)),
                ('est_lu', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('produit_recherche', 'Recherche de produit'), ('expiration_produit', 'Expiration de produit'), ('clic_fiche', 'Clic sur une fiche'), ('suggestion', 'Suggestion de produit')], max_length=30)),
                ('titre', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('lu', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
