# Generated by Django 5.1.7 on 2025-06-05 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_notifications', '0001_initial'),
        ('pharmacien', '0006_delete_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-date_creation']},
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='created_at',
            new_name='date_creation',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='is_read',
            new_name='lu',
        ),
        migrations.AddField(
            model_name='notification',
            name='pharmacy',
            field=models.ForeignKey(default='exit', on_delete=django.db.models.deletion.CASCADE, to='pharmacien.pharmacy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='titre',
            field=models.CharField(default='exit', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('produit_recherche', 'Recherche de produit'), ('expiration_produit', 'Expiration de produit'), ('clic_fiche', 'Clic sur une fiche'), ('suggestion', 'Suggestion de produit')], max_length=30),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
