# Generated by Django 5.1.7 on 2025-06-13 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_notifications', '0001_initial'),
        ('pharmacien', '0007_delete_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expediteur_nom', models.CharField(help_text="Nom de l'expéditeur (utilisateur non authentifié ou nom fourni)", max_length=255)),
                ('expediteur_email', models.EmailField(help_text="Email de l'expéditeur", max_length=254)),
                ('sujet', models.CharField(max_length=255)),
                ('corps', models.TextField()),
                ('date_envoye', models.DateTimeField(auto_now_add=True)),
                ('est_lu', models.BooleanField(default=False)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_recus', to=settings.AUTH_USER_MODEL)),
                ('destinataire_pharmacy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages_recus', to='pharmacien.pharmacy')),
            ],
        ),
    ]
