# Generated by Django 5.1.7 on 2025-06-20 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_notifications', '0002_initial'),
        ('pharmacien', '0004_pharmacy_abonnement_actif_pharmacy_date_essai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='destinataire_pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages_recus_pharmacie', to='pharmacien.pharmacy'),
        ),
        migrations.AlterField(
            model_name='message',
            name='expediteur_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='message',
            name='expediteur_nom',
            field=models.CharField(max_length=255),
        ),
    ]
