# Generated by Django 5.1.7 on 2025-06-22 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_notifications', '0004_notification_content_type_notification_object_id'),
        ('pharmacien', '0004_pharmacy_abonnement_actif_pharmacy_date_essai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='pharmacy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacien.pharmacy'),
        ),
    ]
