# Generated by Django 5.1.7 on 2025-06-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_actif', models.BooleanField(default=False)),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateTimeField(blank=True, null=True)),
                ('test', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Formule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('duree_jours', models.PositiveIntegerField(help_text="Durée de l'abonnement en jours")),
                ('prix', models.DecimalField(decimal_places=2, help_text='Prix en GNF', max_digits=10)),
            ],
        ),
    ]
