# Generated by Django 5.1.7 on 2025-06-15 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonnement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnement',
            name='test',
            field=models.BooleanField(default=True),
        ),
    ]
