# Generated by Django 5.1.7 on 2025-06-15 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonnement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('duree_jours', models.PositiveIntegerField(help_text="Durée de l'abonnement en jours")),
                ('prix', models.DecimalField(decimal_places=2, help_text='Prix en GNF', max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='abonnement',
            name='formule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abonnement.formule'),
        ),
    ]
