# Generated by Django 5.1.7 on 2025-06-16 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abonnement', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abonnement',
            old_name='test',
            new_name='periode_essai',
        ),
    ]
