# Generated by Django 5.1.7 on 2025-06-16 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonnement', '0003_rename_test_abonnement_periode_essai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formule',
            name='duree_jours',
            field=models.FloatField(help_text="Durée de l'abonnement en jours"),
        ),
    ]
