# Generated by Django 5.1.7 on 2025-06-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonnement', '0004_alter_formule_duree_jours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formule',
            name='duree_jours',
        ),
        migrations.AddField(
            model_name='formule',
            name='duree_mois',
            field=models.PositiveIntegerField(default=1, help_text="Durée de l'abonnement en mois"),
            preserve_default=False,
        ),
    ]
