# Generated by Django 5.1.7 on 2025-06-17 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abonnement', '0006_auto_20250617_1921'),
    ]

    operations = [
    ]
