# Generated by Django 5.1.7 on 2025-05-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacien', '0002_message_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='pharmacy',
            options={'verbose_name_plural': 'Pharmacies'},
        ),
        migrations.RemoveField(
            model_name='message',
            name='expediteur',
        ),
        migrations.AddField(
            model_name='message',
            name='expediteur_email',
            field=models.EmailField(default='admin@example.com', help_text="Email de l'expéditeur", max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='expediteur_nom',
            field=models.CharField(default='hawa@gmail.com', help_text="Nom de l'expéditeur (utilisateur non authentifié ou nom fourni)", max_length=255),
            preserve_default=False,
        ),
    ]
