# Generated by Django 5.1.7 on 2025-06-02 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacien', '0003_alter_notification_options_alter_pharmacy_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='destinataire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_recus', to='pharmacien.pharmacy'),
        ),
    ]
