# Generated by Django 5.1.7 on 2025-06-16 18:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacien', '0003_pharmacy_created_at_pharmacy_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='abonnement_actif',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='date_essai',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
