# Generated by Django 5.1.7 on 2025-06-05 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacien', '0005_message_destinataire_pharmacy_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
