# Generated by Django 5.1.7 on 2025-06-13 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacien', '0006_delete_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
